on:
  push:
    branches:
      - master

name: Create release PR or create github release

jobs:
  release-pr:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.SKIM_RS_BOT_APP_ID }}
          private-key: ${{ secrets.SKIM_RS_BOT_PRIVATE_KEY }}
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Install correct toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - id: release-pr
        uses: release-plz/action@v0.5
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        with:
          config: .github/release-plz.toml
